const ALL_DOGS = "ALL_DOGS";
const FILTER_DOGS = "FILTER_DOGS";
const ALL_TEMPERAMENTS = "ALL_TEMPERAMENTS";
const NEW_DOG = "NEW_DOG";
const CHANGE_PAGE = "CHANGE_PAGE";

export {
    ALL_DOGS,
    FILTER_DOGS,
    ALL_TEMPERAMENTS,
    NEW_DOG,
    CHANGE_PAGE,
}