const ALL_DOGS = "ALL_DOGS";
const FILTER_DOGS = "FILTER_DOGS";
const ALL_TEMPERAMENTS = "ALL_TEMPERAMENTS";
const NEW_DOG = "NEW_DOG";
const CHANGE_PAGE = "CHANGE_PAGE";
const FIND_BY_ID = "FIND_BY_ID";
const UPDATE_DATA_FILTER = "UPDATE_DATA_FILTER";
const IS_SHOW_SIDE_BAR = "IS_SHOW_SIDE_BAR";


export {
    ALL_DOGS,
    FILTER_DOGS,
    ALL_TEMPERAMENTS,
    NEW_DOG,
    CHANGE_PAGE,
    FIND_BY_ID,
    UPDATE_DATA_FILTER,
    IS_SHOW_SIDE_BAR
}